### ISSUE TITLE
AttributeError: 'Int64Index' object has no attribute 'tz'

### ISSUE THREAD

**Issue by EgoistaCercis** [quantopian/alphalens#399]
## Problem Description

**Please provide a minimal, self-contained, and reproducible example:**
```python
[Paste code here]
```

**Please provide the full traceback:**
```python
Traceback (most recent call last):
  File "D:/work/paper/test.py", line 95, in <module>
    predictive_factor, pricing, quantiles=5, bins=None, groupby=code_sec, groupby_labels=sec_names)
  File "D:\work\air_systeam\venv\lib\site-packages\alphalens\utils.py", line 832, in get_clean_factor_and_forward_returns
    cumulative_returns,
  File "D:\work\air_systeam\venv\lib\site-packages\alphalens\utils.py", line 263, in compute_forward_returns
    if factor_dateindex.tz != prices.index.tz:
AttributeError: 'Int64Index' object has no attribute 'tz'
```

**Please provide any additional information below:**

## Versions

* Alphalens version: 0.4.0
* Python version: 3.7.7
* Pandas version: 1.2.4
* Matplotlib version: 3.4.2

**Comment by EgoistaCercis** [comment]
Please help me,How to solve this problem?

**Comment by chen0126** [comment]
@EgoistaCercis  Have you solved this problem?
